from config.settings import DATABASE_CONFIG
from sqlalchemy import create_engine, Column, Integer, String, Numeric, Text, DateTime, MetaData
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from datetime import datetime

Base = declarative_base()

class BalanceSheet(Base):
    __tablename__ = 'balance_sheet'
    
    serial_number = Column(Integer, primary_key=True, autoincrement=True)
    stock_code = Column(String(20), nullable=False)
    stock_abbr = Column(String(50))
    monetary_funds = Column(Numeric(20, 2))
    notes_receivable = Column(Numeric(20, 2))
    accounts_receivable = Column(Numeric(20, 2))
    receivables_financing = Column(Numeric(20, 2))
    prepayments = Column(Numeric(20, 2))
    other_receivables = Column(Numeric(20, 2))
    inventory = Column(Numeric(20, 2))
    other_current_assets = Column(Numeric(20, 2))
    total_current_assets = Column(Numeric(20, 2))
    long_term_equity_investment = Column(Numeric(20, 2))
    fixed_assets = Column(Numeric(20, 2))
    construction_in_progress = Column(Numeric(20, 2))
    right_of_use_assets = Column(Numeric(20, 2))
    intangible_assets = Column(Numeric(20, 2))
    goodwill = Column(Numeric(20, 2))
    long_term_deferred_expenses = Column(Numeric(20, 2))
    deferred_tax_assets = Column(Numeric(20, 2))
    other_non_current_assets = Column(Numeric(20, 2))
    total_non_current_assets = Column(Numeric(20, 2))
    total_assets = Column(Numeric(20, 2))
    short_term_borrowings = Column(Numeric(20, 2))
    notes_payable = Column(Numeric(20, 2))
    accounts_payable = Column(Numeric(20, 2))
    advance_receipts = Column(Numeric(20, 2))
    contract_liabilities = Column(Numeric(20, 2))
    employee_benefits_payable = Column(Numeric(20, 2))
    taxes_payable = Column(Numeric(20, 2))
    other_payables = Column(Numeric(20, 2))
    non_current_liabilities_due_within_one_year = Column(Numeric(20, 2))
    other_current_liabilities = Column(Numeric(20, 2))
    total_current_liabilities = Column(Numeric(20, 2))
    long_term_borrowings = Column(Numeric(20, 2))
    lease_liabilities = Column(Numeric(20, 2))
    deferred_tax_liabilities = Column(Numeric(20, 2))
    other_non_current_liabilities = Column(Numeric(20, 2))
    total_non_current_liabilities = Column(Numeric(20, 2))
    total_liabilities = Column(Numeric(20, 2))
    share_capital = Column(Numeric(20, 2))
    capital_reserve = Column(Numeric(20, 2))
    surplus_reserve = Column(Numeric(20, 2))
    undistributed_profit = Column(Numeric(20, 2))
    total_equity_attributable_to_parent = Column(Numeric(20, 2))
    minority_interest = Column(Numeric(20, 2))
    total_equity = Column(Numeric(20, 2))
    total_liabilities_and_equity = Column(Numeric(20, 2))
    report_period = Column(String(20))
    report_year = Column(Integer)
    created_at = Column(DateTime, default=datetime.now)
    updated_at = Column(DateTime, default=datetime.now, onupdate=datetime.now)

class IncomeStatement(Base):
    __tablename__ = 'income_statement'
    
    serial_number = Column(Integer, primary_key=True, autoincrement=True)
    stock_code = Column(String(20), nullable=False)
    stock_abbr = Column(String(50))
    net_profit = Column(Numeric(20, 2))
    net_profit_yoy_growth = Column(Numeric(10, 4))
    other_income = Column(Numeric(20, 2))
    total_operating_revenue = Column(Numeric(20, 2))
    operating_revenue_yoy_growth = Column(Numeric(10, 4))
    operating_expense_cost_of_sales = Column(Numeric(20, 2))
    operating_expense_selling_expenses = Column(Numeric(20, 2))
    operating_expense_administrative_expenses = Column(Numeric(20, 2))
    operating_expense_financial_expenses = Column(Numeric(20, 2))
    operating_expense_rnd_expenses = Column(Numeric(20, 2))
    operating_expense_taxes_and_surcharges = Column(Numeric(20, 2))
    total_operating_expenses = Column(Numeric(20, 2))
    operating_profit = Column(Numeric(20, 2))
    total_profit = Column(Numeric(20, 2))
    asset_impairment_loss = Column(Numeric(20, 2))
    credit_impairment_loss = Column(Numeric(20, 2))
    report_period = Column(String(20))
    report_year = Column(Integer)
    created_at = Column(DateTime, default=datetime.now)
    updated_at = Column(DateTime, default=datetime.now, onupdate=datetime.now)

class CashFlowStatement(Base):
    __tablename__ = 'cash_flow_statement'
    
    serial_number = Column(Integer, primary_key=True, autoincrement=True)
    stock_code = Column(String(20), nullable=False)
    stock_abbr = Column(String(50))
    operating_cf_cash_received_from_sales = Column(Numeric(20, 2))
    operating_cf_tax_refunds_received = Column(Numeric(20, 2))
    operating_cf_other_cash_received = Column(Numeric(20, 2))
    operating_cf_total_inflows = Column(Numeric(20, 2))
    operating_cf_cash_paid_for_goods = Column(Numeric(20, 2))
    operating_cf_cash_paid_to_employees = Column(Numeric(20, 2))
    operating_cf_taxes_paid = Column(Numeric(20, 2))
    operating_cf_other_cash_paid = Column(Numeric(20, 2))
    operating_cf_total_outflows = Column(Numeric(20, 2))
    operating_cf_net_amount = Column(Numeric(20, 2))
    operating_cf_ratio_of_net_cf = Column(Numeric(10, 4))
    investing_cf_cash_received_from_disposal = Column(Numeric(20, 2))
    investing_cf_investment_income_received = Column(Numeric(20, 2))
    investing_cf_cash_from_asset_disposal = Column(Numeric(20, 2))
    investing_cf_other_cash_received = Column(Numeric(20, 2))
    investing_cf_total_inflows = Column(Numeric(20, 2))
    investing_cf_cash_paid_for_assets = Column(Numeric(20, 2))
    investing_cf_cash_paid_for_investment = Column(Numeric(20, 2))
    investing_cf_other_cash_paid = Column(Numeric(20, 2))
    investing_cf_total_outflows = Column(Numeric(20, 2))
    investing_cf_net_amount = Column(Numeric(20, 2))
    investing_cf_ratio_of_net_cf = Column(Numeric(10, 4))
    financing_cf_cash_from_capital_injection = Column(Numeric(20, 2))
    financing_cf_cash_from_borrowings = Column(Numeric(20, 2))
    financing_cf_other_cash_received = Column(Numeric(20, 2))
    financing_cf_total_inflows = Column(Numeric(20, 2))
    financing_cf_cash_paid_for_debt_repayment = Column(Numeric(20, 2))
    financing_cf_cash_paid_for_dividends = Column(Numeric(20, 2))
    financing_cf_other_cash_paid = Column(Numeric(20, 2))
    financing_cf_total_outflows = Column(Numeric(20, 2))
    financing_cf_net_amount = Column(Numeric(20, 2))
    financing_cf_ratio_of_net_cf = Column(Numeric(10, 4))
    report_period = Column(String(20))
    report_year = Column(Integer)
    created_at = Column(DateTime, default=datetime.now)
    updated_at = Column(DateTime, default=datetime.now, onupdate=datetime.now)

class KeyMetrics(Base):
    __tablename__ = 'key_metrics'
    
    serial_number = Column(Integer, primary_key=True, autoincrement=True)
    stock_code = Column(String(20), nullable=False)
    stock_abbr = Column(String(50))
    basic_eps = Column(Numeric(10, 4))
    diluted_eps = Column(Numeric(10, 4))
    bvps = Column(Numeric(10, 4))
    operating_revenue = Column(Numeric(20, 2))
    operating_revenue_yoy_growth = Column(Numeric(10, 4))
    net_profit = Column(Numeric(20, 2))
    net_profit_yoy_growth = Column(Numeric(10, 4))
    net_profit_deducted_non_recurring = Column(Numeric(20, 2))
    net_profit_deducted_non_recurring_yoy_growth = Column(Numeric(10, 4))
    gross_profit_margin = Column(Numeric(10, 4))
    net_profit_margin = Column(Numeric(10, 4))
    roe = Column(Numeric(10, 4))
    total_assets = Column(Numeric(20, 2))
    total_assets_yoy_growth = Column(Numeric(10, 4))
    net_assets = Column(Numeric(20, 2))
    net_assets_yoy_growth = Column(Numeric(10, 4))
    operating_cash_flow = Column(Numeric(20, 2))
    operating_cash_flow_yoy_growth = Column(Numeric(10, 4))
    report_period = Column(String(20))
    report_year = Column(Integer)
    created_at = Column(DateTime, default=datetime.now)
    updated_at = Column(DateTime, default=datetime.now, onupdate=datetime.now)

def get_engine():
    db_url = f"postgresql://{DATABASE_CONFIG['user']}:{DATABASE_CONFIG['password']}@{DATABASE_CONFIG['host']}:{DATABASE_CONFIG['port']}/{DATABASE_CONFIG['database']}"
    return create_engine(db_url)

def get_session():
    engine = get_engine()
    Session = sessionmaker(bind=engine)
    return Session()

def create_tables():
    engine = get_engine()
    Base.metadata.create_all(engine)
    print("Tables created successfully!")

if __name__ == "__main__":
    create_tables()
